# Generated by Django 2.2.3 on 2024-07-09 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0002_auto_20240708_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='catalogo')),
                ('precio', models.IntegerField()),
                ('artista', models.ForeignKey(db_column='nombreArtista', on_delete=django.db.models.deletion.CASCADE, to='artistas.Artista')),
                ('categoria', models.ForeignKey(db_column='nombreCategoria', on_delete=django.db.models.deletion.CASCADE, to='catalogo.Categoria')),
            ],
        ),
    ]
