# Generated by Django 2.2.3 on 2024-07-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('aPaterno', models.CharField(max_length=20)),
                ('aMaterno', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=45)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
